version: "3.7"

services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.3
    container_name: es
    environment:
      - node.name=es
      - network.host=0.0.0.0
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.monitoring.collection.enabled=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    labels:
      co.elastic.logs/module: elasticsearch
      co.elastic.logs/fileset.stdout: access
      co.elastic.logs/fileset.stderr: error
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    expose:
      - "9200"
    networks:
      - elk-network


  filebeat:
    image: docker.elastic.co/beats/filebeat:8.3.3
    container_name: filebeat
    user: root
    environment:
      - setup.kibana.host=http://kibana:5601
      - output.elasticsearch.hosts=["es:9200"]
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=
    volumes:
      - ./data/pipeline/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    expose:
      - 80
    networks:
      - elk-network


  kibana:
    image: docker.elastic.co/kibana/kibana:8.3.3
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://es:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=""
    volumes:
      - ./data/kibana:/usr/share/kibana/data
    ports:
      - 5601:5601
    depends_on:
      - es
    networks:
      - elk-network




networks:
  elk-network:
    driver: bridge
    name: elk-network
    external: true

