version: "3.7"

services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.3
    container_name: es
    environment:
      - node.name=es
      - network.host=0.0.0.0
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.monitoring.collection.enabled=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    labels:
      co.elastic.logs/module: elasticsearch
      co.elastic.logs/fileset.stdout: access
      co.elastic.logs/fileset.stderr: error
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    expose:
      - "9200"
    networks:
      - elk-network


networks:
  elk-network:
    driver: bridge
    name: elk-network
    external: true