version: "3.7"

services:
  kibana:
    image: docker.elastic.co/kibana/kibana:8.3.3
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://es:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=""
    volumes:
      - ./data/kibana:/usr/share/kibana/data
    ports:
      - 5601:5601
    depends_on:
      - es
    networks:
      - elk-network




networks:
  elk-network:
    driver: bridge
    name: elk-network
    external: true